### ISSUE TITLE
Boundary Events in multi-instance Subprocess did not escape correctly

### ISSUE THREAD

**Issue by kvdinker** [bpmnServer/bpmn-server#197]
Hi,

Upon further testing with subprocesses with multiple instances, I found an issue with attached boundary events. In our department loop example, I added a boundary event to cancel the vote, but when I trigger the boundary event, only one sub-process is interrupted and the boundary event flow is started. The second sub-process with the second boundary event is still present.

![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/6334c81a-f2a8-4f04-84c3-67a8a5ea044e)

Furthermore I triggered the last boundary event too, then the normal flow and a second boundary event flow are started, which seems not correct for me. 

![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/02f529c3-ed97-4bf5-9142-7d45b63ff7d2)

As a side node, it looks like a general problem with all types of boundary events and not specific to the cancel boundary event.

Thanks

Code:
```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="sample-diagram" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="Process_1" isExecutable="false">
    <bpmn2:startEvent id="StartEvent_1">
      <bpmn2:outgoing>Flow_1ly2dyb</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:sequenceFlow id="Flow_1ly2dyb" sourceRef="StartEvent_1" targetRef="Activity_1aw4w97" />
    <bpmn2:scriptTask id="Activity_1aw4w97" name="Provide Departments" scriptFormat="JavaScript">
      <bpmn2:incoming>Flow_1ly2dyb</bpmn2:incoming>
      <bpmn2:outgoing>Flow_0hsbjmb</bpmn2:outgoing>
      <bpmn2:script>item.data.includeDepartment = true;
item.data.departments = ["IT", "HR"]</bpmn2:script>
    </bpmn2:scriptTask>
    <bpmn2:sequenceFlow id="Flow_1umlt4b" sourceRef="department" targetRef="Activity_1mx9fl7" />
    <bpmn2:endEvent id="Event_1jag0kh">
      <bpmn2:incoming>Flow_0ri93gq</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_0ri93gq" sourceRef="Activity_1mx9fl7" targetRef="Event_1jag0kh" />
    <bpmn2:userTask id="Activity_1mx9fl7" name="Summerize Votes">
      <bpmn2:incoming>Flow_1umlt4b</bpmn2:incoming>
      <bpmn2:outgoing>Flow_0ri93gq</bpmn2:outgoing>
    </bpmn2:userTask>
    <bpmn2:subProcess id="department" name="Department">
      <bpmn2:incoming>Flow_0hsbjmb</bpmn2:incoming>
      <bpmn2:outgoing>Flow_1umlt4b</bpmn2:outgoing>
      <bpmn2:multiInstanceLoopCharacteristics camunda:collection="$(item.data.departments)" />
      <bpmn2:startEvent id="Event_03fca9f">
        <bpmn2:outgoing>Flow_0exycdh</bpmn2:outgoing>
      </bpmn2:startEvent>
      <bpmn2:sequenceFlow id="Flow_0exycdh" sourceRef="Event_03fca9f" targetRef="Activity_1olobi3" />
      <bpmn2:userTask id="Activity_1olobi3" name="Create Vote">
        <bpmn2:extensionElements>
          <camunda:formData>
            <camunda:formField id="vote" label="Vote" type="boolean" defaultValue="false" />
          </camunda:formData>
        </bpmn2:extensionElements>
        <bpmn2:incoming>Flow_0exycdh</bpmn2:incoming>
        <bpmn2:incoming>Flow_01wzvkh</bpmn2:incoming>
        <bpmn2:outgoing>Flow_1amvo76</bpmn2:outgoing>
      </bpmn2:userTask>
      <bpmn2:exclusiveGateway id="Gateway_0ab9uaw" default="Flow_01wzvkh">
        <bpmn2:incoming>Flow_1amvo76</bpmn2:incoming>
        <bpmn2:outgoing>Flow_02xulvp</bpmn2:outgoing>
        <bpmn2:outgoing>Flow_01wzvkh</bpmn2:outgoing>
      </bpmn2:exclusiveGateway>
      <bpmn2:sequenceFlow id="Flow_1amvo76" sourceRef="Activity_1olobi3" targetRef="Gateway_0ab9uaw" />
      <bpmn2:endEvent id="Event_1ak5jjb">
        <bpmn2:incoming>Flow_02xulvp</bpmn2:incoming>
      </bpmn2:endEvent>
      <bpmn2:sequenceFlow id="Flow_02xulvp" name="vote == &#34;true&#34;" sourceRef="Gateway_0ab9uaw" targetRef="Event_1ak5jjb">
        <bpmn2:conditionExpression xsi:type="bpmn2:tFormalExpression" language="JavaScript">$(item.data.vote=="true")</bpmn2:conditionExpression>
      </bpmn2:sequenceFlow>
      <bpmn2:sequenceFlow id="Flow_01wzvkh" sourceRef="Gateway_0ab9uaw" targetRef="Activity_1olobi3" />
    </bpmn2:subProcess>
    <bpmn2:sequenceFlow id="Flow_0hsbjmb" sourceRef="Activity_1aw4w97" targetRef="department" />
    <bpmn2:boundaryEvent id="Event_0qsfmsy" attachedToRef="department">
      <bpmn2:outgoing>Flow_1mrsorz</bpmn2:outgoing>
      <bpmn2:cancelEventDefinition id="CancelEventDefinition_0rt3smt" />
    </bpmn2:boundaryEvent>
    <bpmn2:sequenceFlow id="Flow_1mrsorz" sourceRef="Event_0qsfmsy" targetRef="Activity_1hcyu4w" />
    <bpmn2:scriptTask id="Activity_1hcyu4w" name="Delete Votes">
      <bpmn2:incoming>Flow_1mrsorz</bpmn2:incoming>
      <bpmn2:outgoing>Flow_1moj2o6</bpmn2:outgoing>
    </bpmn2:scriptTask>
    <bpmn2:endEvent id="Event_1s6yeg2">
      <bpmn2:incoming>Flow_1moj2o6</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_1moj2o6" sourceRef="Activity_1hcyu4w" targetRef="Event_1s6yeg2" />
  </bpmn2:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNEdge id="Flow_0hsbjmb_di" bpmnElement="Flow_0hsbjmb">
        <di:waypoint x="320" y="258" />
        <di:waypoint x="360" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0ri93gq_di" bpmnElement="Flow_0ri93gq">
        <di:waypoint x="1140" y="258" />
        <di:waypoint x="1192" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1umlt4b_di" bpmnElement="Flow_1umlt4b">
        <di:waypoint x="990" y="258" />
        <di:waypoint x="1040" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1ly2dyb_di" bpmnElement="Flow_1ly2dyb">
        <di:waypoint x="178" y="258" />
        <di:waypoint x="220" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1mrsorz_di" bpmnElement="Flow_1mrsorz">
        <di:waypoint x="1008" y="360" />
        <di:waypoint x="1040" y="360" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1moj2o6_di" bpmnElement="Flow_1moj2o6">
        <di:waypoint x="1140" y="360" />
        <di:waypoint x="1192" y="360" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="142" y="240" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1trqr8z_di" bpmnElement="Activity_1aw4w97">
        <dc:Bounds x="220" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1jag0kh_di" bpmnElement="Event_1jag0kh">
        <dc:Bounds x="1192" y="240" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1oo3z2k_di" bpmnElement="Activity_1mx9fl7">
        <dc:Bounds x="1040" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0768bpi_di" bpmnElement="Activity_1hcyu4w">
        <dc:Bounds x="1040" y="320" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1s6yeg2_di" bpmnElement="Event_1s6yeg2">
        <dc:Bounds x="1192" y="342" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0dsqa5j_di" bpmnElement="department" isExpanded="true">
        <dc:Bounds x="360" y="137" width="630" height="263" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_01wzvkh_di" bpmnElement="Flow_01wzvkh">
        <di:waypoint x="750" y="285" />
        <di:waypoint x="750" y="340" />
        <di:waypoint x="580" y="340" />
        <di:waypoint x="580" y="300" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_02xulvp_di" bpmnElement="Flow_02xulvp">
        <di:waypoint x="775" y="260" />
        <di:waypoint x="872" y="260" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="787" y="242" width="66" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1amvo76_di" bpmnElement="Flow_1amvo76">
        <di:waypoint x="630" y="260" />
        <di:waypoint x="725" y="260" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0exycdh_di" bpmnElement="Flow_0exycdh">
        <di:waypoint x="438" y="260" />
        <di:waypoint x="530" y="260" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_03fca9f_di" bpmnElement="Event_03fca9f">
        <dc:Bounds x="402" y="242" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0f58zap_di" bpmnElement="Activity_1olobi3">
        <dc:Bounds x="530" y="220" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_0ab9uaw_di" bpmnElement="Gateway_0ab9uaw" isMarkerVisible="true">
        <dc:Bounds x="725" y="235" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1ak5jjb_di" bpmnElement="Event_1ak5jjb">
        <dc:Bounds x="872" y="242" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0rxj1px_di" bpmnElement="Event_0qsfmsy">
        <dc:Bounds x="972" y="342" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>

```

**Comment by ralphhanna** [comment]
Thanks for reporting this a fix is coming soon, it will cancel all items in the loop

**Comment by ralphhanna** [comment]
This was fixed in the latest release

**Comment by kvdinker** [comment]
Great, thanks for the fix :)
I tested the new release directly and the example above is working just fine. But I found some small related bug. If we add an Gateway in front of the subprocess, the boundary Event throws an error due to a missing token. Looks a bit like Issue #186, because an empty dummy task between Gateway and Subprocess can fix the problem.

![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/23265591-e1e9-4119-b1a0-c2100143d355)
![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/ba4c8860-cde1-48d6-8351-d3b6d00c9384)

Workaround:

![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/bbc3dd44-edc9-4c3a-8eba-e5ac0eda7746)


Code:
```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="sample-diagram" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="Process_1" isExecutable="false">
    <bpmn2:startEvent id="StartEvent_1">
      <bpmn2:outgoing>Flow_1ly2dyb</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:sequenceFlow id="Flow_1ly2dyb" sourceRef="StartEvent_1" targetRef="Activity_1aw4w97" />
    <bpmn2:scriptTask id="Activity_1aw4w97" name="Provide Departments" scriptFormat="JavaScript">
      <bpmn2:incoming>Flow_1ly2dyb</bpmn2:incoming>
      <bpmn2:outgoing>Flow_1ifl7lb</bpmn2:outgoing>
      <bpmn2:script>item.data.includeDepartment = true;
item.data.departments = ["IT", "HR"]</bpmn2:script>
    </bpmn2:scriptTask>
    <bpmn2:sequenceFlow id="Flow_1umlt4b" sourceRef="department" targetRef="Activity_1mx9fl7" />
    <bpmn2:endEvent id="Event_1jag0kh">
      <bpmn2:incoming>Flow_0ri93gq</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_0ri93gq" sourceRef="Activity_1mx9fl7" targetRef="Event_1jag0kh" />
    <bpmn2:userTask id="Activity_1mx9fl7" name="Summerize Votes">
      <bpmn2:incoming>Flow_1umlt4b</bpmn2:incoming>
      <bpmn2:outgoing>Flow_0ri93gq</bpmn2:outgoing>
    </bpmn2:userTask>
    <bpmn2:subProcess id="department" name="Department">
      <bpmn2:incoming>Flow_034gj5b</bpmn2:incoming>
      <bpmn2:outgoing>Flow_1umlt4b</bpmn2:outgoing>
      <bpmn2:multiInstanceLoopCharacteristics camunda:collection="$(item.data.departments)" />
      <bpmn2:startEvent id="Event_03fca9f">
        <bpmn2:outgoing>Flow_0exycdh</bpmn2:outgoing>
      </bpmn2:startEvent>
      <bpmn2:sequenceFlow id="Flow_0exycdh" sourceRef="Event_03fca9f" targetRef="Activity_1olobi3" />
      <bpmn2:userTask id="Activity_1olobi3" name="Create Vote">
        <bpmn2:extensionElements>
          <camunda:formData>
            <camunda:formField id="vote" label="Vote" type="boolean" defaultValue="false" />
          </camunda:formData>
        </bpmn2:extensionElements>
        <bpmn2:incoming>Flow_0exycdh</bpmn2:incoming>
        <bpmn2:incoming>Flow_01wzvkh</bpmn2:incoming>
        <bpmn2:outgoing>Flow_1amvo76</bpmn2:outgoing>
      </bpmn2:userTask>
      <bpmn2:exclusiveGateway id="Gateway_0ab9uaw" default="Flow_01wzvkh">
        <bpmn2:incoming>Flow_1amvo76</bpmn2:incoming>
        <bpmn2:outgoing>Flow_02xulvp</bpmn2:outgoing>
        <bpmn2:outgoing>Flow_01wzvkh</bpmn2:outgoing>
      </bpmn2:exclusiveGateway>
      <bpmn2:sequenceFlow id="Flow_1amvo76" sourceRef="Activity_1olobi3" targetRef="Gateway_0ab9uaw" />
      <bpmn2:endEvent id="Event_1ak5jjb">
        <bpmn2:incoming>Flow_02xulvp</bpmn2:incoming>
      </bpmn2:endEvent>
      <bpmn2:sequenceFlow id="Flow_02xulvp" name="vote == &#34;true&#34;" sourceRef="Gateway_0ab9uaw" targetRef="Event_1ak5jjb">
        <bpmn2:conditionExpression xsi:type="bpmn2:tFormalExpression" language="JavaScript">$(item.data.vote=="true")</bpmn2:conditionExpression>
      </bpmn2:sequenceFlow>
      <bpmn2:sequenceFlow id="Flow_01wzvkh" sourceRef="Gateway_0ab9uaw" targetRef="Activity_1olobi3" />
    </bpmn2:subProcess>
    <bpmn2:sequenceFlow id="Flow_1mrsorz" sourceRef="Event_0qsfmsy" targetRef="Activity_1hcyu4w" />
    <bpmn2:scriptTask id="Activity_1hcyu4w" name="Delete Votes">
      <bpmn2:incoming>Flow_1mrsorz</bpmn2:incoming>
      <bpmn2:outgoing>Flow_1moj2o6</bpmn2:outgoing>
    </bpmn2:scriptTask>
    <bpmn2:endEvent id="Event_1s6yeg2">
      <bpmn2:incoming>Flow_1moj2o6</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_1moj2o6" sourceRef="Activity_1hcyu4w" targetRef="Event_1s6yeg2" />
    <bpmn2:exclusiveGateway id="Gateway_14r336f" default="Flow_0r8wzcu">
      <bpmn2:incoming>Flow_1ifl7lb</bpmn2:incoming>
      <bpmn2:outgoing>Flow_034gj5b</bpmn2:outgoing>
      <bpmn2:outgoing>Flow_0r8wzcu</bpmn2:outgoing>
    </bpmn2:exclusiveGateway>
    <bpmn2:sequenceFlow id="Flow_1ifl7lb" sourceRef="Activity_1aw4w97" targetRef="Gateway_14r336f" />
    <bpmn2:sequenceFlow id="Flow_034gj5b" sourceRef="Gateway_14r336f" targetRef="department">
      <bpmn2:conditionExpression xsi:type="bpmn2:tFormalExpression" language="JavaScript">$(item.data.includeDepartment==true)</bpmn2:conditionExpression>
    </bpmn2:sequenceFlow>
    <bpmn2:boundaryEvent id="Event_0qsfmsy" attachedToRef="department">
      <bpmn2:outgoing>Flow_1mrsorz</bpmn2:outgoing>
      <bpmn2:cancelEventDefinition id="CancelEventDefinition_1418bcw" />
    </bpmn2:boundaryEvent>
    <bpmn2:endEvent id="Event_1isufif">
      <bpmn2:incoming>Flow_0r8wzcu</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_0r8wzcu" sourceRef="Gateway_14r336f" targetRef="Event_1isufif" />
  </bpmn2:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNEdge id="Flow_1ly2dyb_di" bpmnElement="Flow_1ly2dyb">
        <di:waypoint x="228" y="258" />
        <di:waypoint x="270" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1ifl7lb_di" bpmnElement="Flow_1ifl7lb">
        <di:waypoint x="370" y="258" />
        <di:waypoint x="415" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0ri93gq_di" bpmnElement="Flow_0ri93gq">
        <di:waypoint x="1630" y="340" />
        <di:waypoint x="1752" y="340" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1umlt4b_di" bpmnElement="Flow_1umlt4b">
        <di:waypoint x="1340" y="340" />
        <di:waypoint x="1530" y="340" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1mrsorz_di" bpmnElement="Flow_1mrsorz">
        <di:waypoint x="1358" y="180" />
        <di:waypoint x="1530" y="180" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1moj2o6_di" bpmnElement="Flow_1moj2o6">
        <di:waypoint x="1630" y="180" />
        <di:waypoint x="1752" y="180" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_034gj5b_di" bpmnElement="Flow_034gj5b">
        <di:waypoint x="465" y="258" />
        <di:waypoint x="660" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0r8wzcu_di" bpmnElement="Flow_0r8wzcu">
        <di:waypoint x="440" y="233" />
        <di:waypoint x="440" y="173" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_1jag0kh_di" bpmnElement="Event_1jag0kh">
        <dc:Bounds x="1752" y="322" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1oo3z2k_di" bpmnElement="Activity_1mx9fl7">
        <dc:Bounds x="1530" y="300" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0768bpi_di" bpmnElement="Activity_1hcyu4w">
        <dc:Bounds x="1530" y="140" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1s6yeg2_di" bpmnElement="Event_1s6yeg2">
        <dc:Bounds x="1752" y="162" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="192" y="240" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_14r336f_di" bpmnElement="Gateway_14r336f" isMarkerVisible="true">
        <dc:Bounds x="415" y="233" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1isufif_di" bpmnElement="Event_1isufif">
        <dc:Bounds x="422" y="137" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1trqr8z_di" bpmnElement="Activity_1aw4w97">
        <dc:Bounds x="270" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0dsqa5j_di" bpmnElement="department" isExpanded="true">
        <dc:Bounds x="660" y="137" width="680" height="263" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_01wzvkh_di" bpmnElement="Flow_01wzvkh">
        <di:waypoint x="1060" y="285" />
        <di:waypoint x="1060" y="340" />
        <di:waypoint x="870" y="340" />
        <di:waypoint x="870" y="300" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_02xulvp_di" bpmnElement="Flow_02xulvp">
        <di:waypoint x="1085" y="260" />
        <di:waypoint x="1242" y="260" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="1098" y="243" width="66" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1amvo76_di" bpmnElement="Flow_1amvo76">
        <di:waypoint x="920" y="260" />
        <di:waypoint x="1035" y="260" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0exycdh_di" bpmnElement="Flow_0exycdh">
        <di:waypoint x="728" y="260" />
        <di:waypoint x="820" y="260" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Gateway_0ab9uaw_di" bpmnElement="Gateway_0ab9uaw" isMarkerVisible="true">
        <dc:Bounds x="1035" y="235" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0f58zap_di" bpmnElement="Activity_1olobi3">
        <dc:Bounds x="820" y="220" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_03fca9f_di" bpmnElement="Event_03fca9f">
        <dc:Bounds x="692" y="242" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1ak5jjb_di" bpmnElement="Event_1ak5jjb">
        <dc:Bounds x="1242" y="242" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0j16ufx_di" bpmnElement="Event_0qsfmsy">
        <dc:Bounds x="1322" y="162" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>

```

**Comment by ralphhanna** [comment]
Thanks again for noticing this one, it fell through the cracks..
Fixed in Release 2.2.1

**Comment by kvdinker** [comment]
No worries. I´m still getting the same error with the new release.
![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/36864eb2-9975-4450-a717-363261182570)

**Comment by ralphhanna** [comment]
Can you please verify, I have running example here
https://bpmn.omniworkflow.com/instanceDetails?id=c1bc5682-8e1f-4b3c-92e4-7440e397b570

![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/7b847fe2-4461-48cc-93c0-2b2cb1d5c4ee)

https://bpmn.omniworkflow.com/model/edit/Issue197A/

**Comment by ralphhanna** [comment]
Fixed in release 2.2.2
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/6058a69a-fddb-49f7-a21c-f88f03117914)

**Comment by kvdinker** [comment]
Great, thank you :)
 With the new release the cancel is working without an error
