### ISSUE TITLE
Even after the flow is closed, the tokens at inclusive gateway are still active

### ISSUE THREAD

**Issue by shashank-yelluri** [bpmnServer/bpmn-server#242]
Hello @ralphhanna 

I've tried to configure a workflow where i have several paths opened with an inclusive gateway. The user tasks on the paths are deactivated, but the tokens at the inclusive gateway are still open and hence the whole status of the workflow is "running". Is there anything wrong in the configuration ? 
Attaching the screenshot for reference.

<img width="730" alt="Image" src="https://github.com/user-attachments/assets/b0969e29-a5ea-464f-8e71-c518028c477f" />

**Comment by shashank-yelluri** [comment]
@ralphhanna - gentle reminder on this 😬 
I really need your inputs on this to understand whether it is a genuine issue or something wrong with the configuration ? I see the user tasks are getting deactivated, but the tokens at the inclusive the still in active mode, due to which the workflow status is "running".

**Comment by ralphhanna** [comment]
Sorry, that was a bug fixed in release 2.2.18
Thanks

**Comment by shashank-yelluri** [comment]
@ralphhanna - i've tried installing the `2.2.18` version and still seeing the same problem.

**Comment by shashank-yelluri** [comment]
Attaching the screenshot as a reference,

<img width="1029" alt="Image" src="https://github.com/user-attachments/assets/c084df1a-a268-494e-8ac6-2a24b0610dba" />

**Comment by ralphhanna** [comment]
Sorry, I don't see the problem from the diagram.
Can you please send me the bpmn file again with instructions on how to create the error.

Just a note on the process design; If the difference between Approver_01_1 and Approver_02_1 is just the person assigned to the task, why not dynamically assign the user.

See https://bpmnserver.github.io/docs/security/

**Comment by shashank-yelluri** [comment]
```
async determineWorkflow() {
        return [
            {
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Officers Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "RM Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            {
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Risk Officers Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Compliance Officers Team",
                      "minApprovers": 2
                    }
                  ]
                }
              ]
            },
            {
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Controllers Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            {
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "CFO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Vice President Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Senior Ops Team",
                      "minApprovers": 3
                    }
                  ]
                }
              ]
            },
            {
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Board Member",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "CEO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Regulator",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            }
          ];
    }
```

**Comment by ralphhanna** [comment]
Let me take a shot at the business logic:
1. Every workflow is about a particular Issue that needs several approvals
2. a User **Maker** select the Issue Type, based on that we determine
- the Group that performs the approval
- the minimum number of users of that group that need to approve

## Option 1: All uses can approve at same time
3. based on the above:
- We start as many task of approvers as required
- When approval is complete we end the workflow

<img width="706" alt="Image" src="https://github.com/user-attachments/assets/7fc7244b-830b-4cc2-8710-3c2dcb8b8047" />

Only the minimum number of approvals is allowed.

## Option 2: Approval in serial
3. based on the above:
- We start one task at a time until number is complete
- When approval is complete we end the workflow

<img width="689" alt="Image" src="https://github.com/user-attachments/assets/910fb2d4-30e1-46b4-a9a4-07c68f8c7da7" />

## Option 3: Assign Unique User Tasks to each user in the group and cancel tasks when Minimum number of approval is reach.
This is also possible, let me know if you need it.

Thanks

**Comment by shashank-yelluri** [comment]
@ralphhanna - you understood the almost problem. 

But based on the JSON i've shared above, we have cxLevels and each level will have rules and sub rules 

CX Levels (Sequential)
Rules (Combination of ANDs)
Sub-Rules (Combination of ORs)

Now, if we see that in levels, let me explain the process at level 1. 
The work item has to be offered to all the rules. (as it is a combination of ORs, so the collection gateway is exclusive)

Now, the rule can have sub rules and again the work item has to be offered to all groups  (as it is a combination of ANDs, so the collection gateway is parallel)

Your second option is not really at the task level. As we are seeing task is offered to single group and it is a sub rule. The serial nature will be for the whole process of CX Levels as i've mentioned above. 

Your third option, i don't really want to cancel cancel the process, as i've reached to the END_EVENT, I'd like to end the workflow. If the work item is approved and satisfies the condition it can go to the next set of level (CX Level 2) which will further have the same combination of ANDs / ORs (calling them as rules & sub rules)

I didn't really able to think from your shoes completely. If you could share me a sample BPMN which solves the problem i've shared with the above BPMN and the details i've mentioned here, that'll be really helpful. 

Thank You 😄

**Comment by shashank-yelluri** [comment]
Also in your shared .bpmn file, it is a very straight forward one and thin layer of the complete business logic. Instead of asking to select a group name and then the minimum approvers, we already have them and that too with the combination of ORs and ANDs. That is the whole reason why , i had to go with the combination of exclusive, inclusive & parallel gateways in one level. 

After one level, the same process would continue for the next levels. Like this, i need to have a maximum of 5 levels. 

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/7aa40eec-afdf-400f-af50-d1a8c986554c" />

Hope you remember this ? I've tried to configure something like this and it didn't work. Now, inside the inner sub process, i need to have one more exclusive condition attached to each user task to see the ACTION field. If any person from any group (set of approvers) reject the work item, we need to close the complete workflow and move the status of the work item to "end".

I've read your comment that, the above mentioned file would really work with release `2.218`, but i haven't really tried that out as i was half way through with this complicated and lengthy approach to solve my problem. 

But if you could really construct similar to the one i've shared above and ad a functionality to end the workflow if any approver rejects it, that is like beauty. 

Along with this, if you remember one more discussion i've opened to invoke the multiple user tasks. Now, you probably get my point as you have the complete workflow. 

Let's say i have two rules, (Level 1)
1 from Group A AND 2 from Group B
OR 
1 from Group C AND 2 from Group A

Now i'll fit this into the workflow i've shared first. As i have both the sets as two paths in inclusive gateway, the moment anyone belongs to Group A approves the work item, i need to invoke two task IDs as i have two user tasks at two different paths of inclusive gateway. 

This is another problem that i was facing and currently have made a work around to iterate the items based on the candidateGroups with the combination of elementId and invoking them programatically one by one. But please share me your approach on this as well. 

Please explore these questions, when your time permits. Highly respect your time and would be really helpful to speed up my development work with any of your small suggestions / inputs. 

Thank You.

**Comment by ralphhanna** [comment]
<img width="1100" alt="Image" src="https://github.com/user-attachments/assets/13da6b1a-4033-4c9c-bd33-c95e6acc6bc4" />

Revised Json
```json
  [
            { Stage: "A",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Officers Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "RM Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            { Stage: "B",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Risk Officers Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Compliance Officers Team",
                      "minApprovers": 2
                    }
                  ]
                }
              ]
            },
            { Stage: "C",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Controllers Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            {
		Stage: "D",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "CFO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Vice President Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Senior Ops Team",
                      "minApprovers": 3
                    }
                  ]
                }
              ]
            },
            {
		Stage: "E",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Board Member",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "CEO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Regulator",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            }
          ];
    }
```

**Comment by shashank-yelluri** [comment]
@ralphhanna - could you please share the bpmn file for the above file ? Dying to test it in bpmn-web and really thinking on how it handles multiple rules and sub rules execution 🤯

**Comment by shashank-yelluri** [comment]
I mean really, just a sub process with one user task. I think I’ve spent a week breaking my head to come with the data structure to store the rules and sub rules, so that I can fit in the data rightly to the workflow and another week or so to construct this vast and huge workflow 😢 

Ok let me vent once the file actually works 😬

**Comment by ralphhanna** [comment]
Let me try again.
- An Issue requires multiple stages of approval, Each called **Stage**
- An Approval Stage requires multiple teams to approve, called **Team**
- Each team requires a minimum number of approvers.
- Teams can approve in parallel 
- Once all Teams complete approval, workflow moves to next **Stage**

**Comment by shashank-yelluri** [comment]
@ralphhanna - this is perfect.

**Comment by shashank-yelluri** [comment]
@ralphhanna - also. the "Team" involves multiple teams statement is little confusing. So, till stage it's fine, each stage will have set of rules (1 from Group AND 2 from Group C AND 5 from Group F) and each stage has upto 6 rules. Not only individual rule can approve in parallel, multiple rules can also be approve in parallel. 
Now if any 1 rule completes it path, then we consider the stage to be done and move forward. 

Example, 

# STAGE 1
1 from Group A AND 2 from Group B  -> RULE 
OR 
2 from Group B AND 1 from GROUP C AND 1 from Group D -> Rule 
OR
4 from Group F -> Rule 
OR 
5 from Group E AND 2 from Group A -> Rule

Note: Here, the work items has to be offered to all the groups involved at this stage. Not rule per rule.

# STAGE 2
1 from Group A AND 2 from Group B  -> RULE 
OR 
2 from Group B AND 1 from GROUP C AND 1 from Group D -> Rule 
OR
4 from Group F -> Rule 
OR 
5 from Group E AND 2 from Group A -> Rule

... upto 5 stages in sequence (one after the other)

**Comment by ralphhanna** [comment]
Please check this

[Multi-Approval.bpmn.txt](https://github.com/user-attachments/files/18974592/Multi-Approval.bpmn.txt)

Add the following code in your AppServices.ts
```ts

    async getNoOfApprovers(context) {
      let keys=context.itemsKey.split('.');
      let stageTeams=this.rules[keys[0]];
      

      for(let i=0;i<stageTeams.length;i++)
      {
        if (stageTeams[i].groupName===keys[1])
          return stageTeams[i].minApprovers;
      }
      
      return 0;

    }

    get rules() {
        return  {
            "Stage_A": 
                [
                    {"groupName": "Treasury Officers Team","minApprovers": 2},
                    {"groupName": "RM Team","minApprovers": 1},
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                ],
            "Stage_B":
               [
                    {
                      "groupName": "Risk Officers Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Compliance Officers Team",
                      "minApprovers": 2
                    }
                  ]
            , "Stage_C":
                [
                    {
                      "groupName": "Treasury Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Controllers Team",
                      "minApprovers": 1
                    }
                  ]
                 ,
            "Stage_D":
               [
                    {
                      "groupName": "CFO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Vice President Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "Senior Ops Team",
                      "minApprovers": 3
                    }
                  ]
                ,
            "Stage_E": 
               [
                    {
                      "groupName": "Board Member",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "CEO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Regulator",
                      "minApprovers": 1
                    }
                  ]
                };
    }
```

**Comment by ralphhanna** [comment]
<img width="521" alt="Image" src="https://github.com/user-attachments/assets/9b371a31-e30a-44ee-87c9-ca5384c84abf" />

**Comment by shashank-yelluri** [comment]
@ralphhanna - you are mentioning all the combinations under one "stage" like this, 
[
                    {"groupName": "Treasury Officers Team","minApprovers": 2},
                    {"groupName": "RM Team","minApprovers": 1},
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
]

But in this, some of them are AND and that some are classified into ORs

Like, 

"rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Officers Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "RM Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]

Any reason behind clubbing them ? 
It's like one member of "HR Head Team" approves, then the stage is consider to be done. 
OR 
1 member from Director Team 
OR 
1 Operations Head Team AND 1 from Finance 
OR 
....

**Comment by shashank-yelluri** [comment]
@ralphhanna - Ok. I could see something that you've engineered to get the stage split and all, which i'll get deeper into it. But before that, executing the HR Head Team should ideally end the workflow or the next stage should open, but many items of STAGE_A are still showing to execute. Could you please help me with that ?

<img width="1797" alt="Image" src="https://github.com/user-attachments/assets/c9e9aa27-f689-465b-94e9-a67f41f21c88" />

**Comment by shashank-yelluri** [comment]
@ralphhanna - crazy approach. I went through the functions and the workflow, but my question remains same after that. We need to have that differentiation with AND OR combinations in one stage.

**Comment by ralphhanna** [comment]
Please explain above statement, give concrete examples
The flow is like this:
- Invoke one stage at a time in serial mode, once one stage is completes it starts next stage
- Each Stage requires multiple teams
- Each Team requires one or more user from that team

**Comment by shashank-yelluri** [comment]
@ralphhanna,

1. Correct 
2. slight modification here, teams are further classified into ORs. 
Example,  
One member from HR team and 2 members from finance team 
OR
2 Board members 
OR 
1 finance and 1 head hr team 
3. Correct. 

1 & 3 points are to the point. But second one has its split with ORs. Each OR will have the combination of ANDs

**Comment by shashank-yelluri** [comment]
@ralphhanna - this revised JSON of yours is the best example i can put, 

[
            { Stage: "A",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Officers Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "RM Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            { Stage: "B",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Risk Officers Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Compliance Officers Team",
                      "minApprovers": 2
                    }
                  ]
                }
              ]
            },
            { Stage: "C",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Controllers Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            {
		Stage: "D",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "CFO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Vice President Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Senior Ops Team",
                      "minApprovers": 3
                    }
                  ]
                }
              ]
            },
            {
		Stage: "E",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Board Member",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "CEO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Regulator",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            }
          ];
    }

With the combination of stages, rules (OR) and sub rules (AND)
Each sub rule carries groupName and minimumApprovers

**Comment by ralphhanna** [comment]
Ok, here is a sample run:
```text
10 - Stage_A.Treasury Officers Team.1 - end
12 - Stage_A.Treasury Officers Team.2 - end
14 - Stage_A.RM Team.1 - Cancelled
16 - Stage_A.Finance Team.1 - Cancelled
18 - Stage_A.Finance Team.2 - Cancelled
20 - Stage_A.Operations Head Team.1 - Cancelled
22 - Stage_A.Finance Team.1 - Cancelled
24 - Stage_A.Directors Team.1 - Cancelled
26 - Stage_A.HR Head Team.1 - Cancelled
38 - Stage_B.Risk Officers Team.1 - end
40 - Stage_B.Compliance Officers Team.1 - Cancelled
42 - Stage_B.Compliance Officers Team.2 - Cancelled
64 - Stage_C.Treasury Head Team.1 - Cancelled
66 - Stage_C.Finance Controllers Team.1 - end
80 - Stage_D.CFO.1 - Cancelled
82 - Stage_D.Vice President Team.1 - Cancelled
84 - Stage_D.Vice President Team.2 - Cancelled
86 - Stage_D.Senior Ops Team.1 - end
88 - Stage_D.Senior Ops Team.2 - end
90 - Stage_D.Senior Ops Team.3 - end
104 - Stage_E.Board Member.1 - wait
106 - Stage_E.CEO.1 - wait
108 - Stage_E.Regulator.1 - wait
```
The above, I ran Stage A-D, waiting for Stage E.

Here is the bpmn 

[Multi-level-Approval.bpmn.txt](https://github.com/user-attachments/files/18977520/Multi-level-Approval.bpmn.txt)

AppServices.ts Code:
```ts

    IsApprovalDone(context) {
      // get the minApprovers
      console.log(context);
      let keys=context.itemKey.split('.');
      let stage=keys[0];
      let team=keys[1];
      let minApprovers=this.getMinApprovers(stage,team);
      console.log(minApprovers);
      let allItems=context.token.execution.getItems();
      let completed=allItems.filter(i=>{
        return (i.status=='end' && i.type=='bpmn:UserTask' && i.itemKey.startsWith(stage+'.'+team))
      });
      if (completed.length==minApprovers) 
        return true;
      else
        return false;
      
    }
    async getApprovers(context) {
      
      let stage=context.itemsKey.split('.');
      let stageTeams=this.rules[stage];

      let items=[];

      for(let t=0;t<stageTeams.length;t++)
      {
          ;
          for(let i=0;i<stageTeams[t].minApprovers;i++)
          {
            items.push(''+stageTeams[t].groupName+'.'+(i+1))
          }
      }
      
      return items;

    }
    getMinApprovers(stage,team) {
      
      let stageTeams=this.rules[stage];

      for(let t=0;t<stageTeams.length;t++)
      {
        if (stageTeams[t].groupName==team)
          return stageTeams[t].minApprovers;
      }
      return 0;

    }

    get rules() {
        return  {
            "Stage_A": 
                [
                    {"groupName": "Treasury Officers Team","minApprovers": 2},
                    {"groupName": "RM Team","minApprovers": 1},
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                ],
            "Stage_B":
               [
                    {
                      "groupName": "Risk Officers Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Compliance Officers Team",
                      "minApprovers": 2
                    }
                  ]
            , "Stage_C":
                [
                    {
                      "groupName": "Treasury Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Controllers Team",
                      "minApprovers": 1
                    }
                  ]
                 ,
            "Stage_D":
               [
                    {
                      "groupName": "CFO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Vice President Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "Senior Ops Team",
                      "minApprovers": 3
                    }
                  ]
                ,
            "Stage_E": 
               [
                    {
                      "groupName": "Board Member",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "CEO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Regulator",
                      "minApprovers": 1
                    }
                  ]
                };
    }
```

**Comment by shashank-yelluri** [comment]
@ralphhanna - this is right when every object under each stage is one rule. You are treating all of them with the difference of OR.
That is why, any one group satisfies the minimum approvals, you are moving the token to next stage. But Inside each stage, you are assuming like this, 

"$OR": 
                [
                    {"groupName": "Treasury Officers Team","minApprovers": 2},
                    {"groupName": "RM Team","minApprovers": 1},
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                ]

But it'll be something like this 

"$OR": [
    {
        "$AND": [
            {
                "groupName": "Treasury Officers Team",
                "minApprovers": 2
            },
            {
                "groupName": "RM Team",
                "minApprovers": 1
            }
        ]
    },
    {
        "$AND": [
            {
                "groupName": "Finance Team",
                "minApprovers": 2
            },
            {
                "groupName": "Operations Head Team",
                "minApprovers": 1
            }
        ]
    },
    {
        "$AND": [
            {
                "groupName": "Finance Team",
                "minApprovers": 1
            }
        ]
    },
    {
        "$AND": [
            {
                "groupName": "Directors Team",
                "minApprovers": 1
            }
        ]
    },
    {
        "$AND": [
            {
                "groupName": "HR Head Team",
                "minApprovers": 1
            }
        ]
    }
]

**Comment by shashank-yelluri** [comment]
@ralphhanna - which means, we should not proceed forward until any one $AND satisfies in the array of $OR. Here $OR is our stage.

**Comment by ralphhanna** [comment]
Ok, you just need to modify rules method adding $and , $or

Then modify the method IsApprovalComplete to comply

**Comment by shashank-yelluri** [comment]
@ralphhanna - didn't quite get it. How can one user task solve this problem ? I've shared one image on top, may be we need to configure in that way ? Or please help me with the changes you are suggesting, not able to decipher from your comment on what changes should i make ?
Thank You and sorry for all the trouble

**Comment by shashank-yelluri** [comment]
<img width="1797" alt="Image" src="https://github.com/user-attachments/assets/1658b930-e1d0-4a24-ae46-c7fca2cff998" />

IMO, it should be something like this.

**Comment by shashank-yelluri** [comment]
@ralphhanna - any luck :( ??
Have any solution to the problem ?

Thank You

**Comment by ralphhanna** [comment]
OK, I have tried it by declaring sample rules as bpmn design as follows:

<img width="835" alt="Image" src="https://github.com/user-attachments/assets/07af64d9-cc21-4d97-b168-8e8df2efeab3" />

The left is OR , right is And

It worked for me fine.
I know this is not a complete model, but you can go ahead and modify it, hope that you got the idea.

Here is the bpmn file

[Multi-Approval.bpmn (2).txt](https://github.com/user-attachments/files/18996257/Multi-Approval.bpmn.2.txt)

**Comment by ralphhanna** [comment]
Here is another model:

<img width="637" alt="Image" src="https://github.com/user-attachments/assets/0e459e01-2720-4b0d-adfd-53e866d99292" />

[or-ands.bpmn.txt](https://github.com/user-attachments/files/18996543/or-ands.bpmn.txt)

I am  signing off for now...

If you discover a bug please submit me a new model with the bug

**Comment by shashank-yelluri** [comment]
@ralphhanna - sure, let me go through the shared examples and let you know if i find any. Once again thank you for your time in configuring & testing these models.

**Comment by ralphhanna** [comment]
Have you made any progress in this, here is my revised model.

[Complex Approval Process.bpmn.txt](https://github.com/user-attachments/files/19015341/Complex.Approval.Process.bpmn.txt)

Question:  Can a user Reject the approval? what is the impact on flow?

**Comment by shashank-yelluri** [comment]
@ralphhanna - I cannot use the parallel gateway, because i need to have conditions there. Hence i went ahead with the inclusive gateway and facing the same issue (tokens are active on the gateways).

To answer your question, 
Any reject happens at any moment, we need to immediately end the workflow. Is it possible to do ?

**Comment by ralphhanna** [comment]
Please submit your revised model with the inclusive gateway.

For reject to cancel the process you have to do this:

<img width="1219" alt="Image" src="https://github.com/user-attachments/assets/c1a52e70-668b-4aa6-b6ee-daa52ae12174" />

And add a trigger `end` at each User Activity to escalate the process. code like this:
```js
if (item.data.approval=='reject')
   return {escalation:'rejected'};
```
assuming that the item has `approval` is either `approve` or `reject`

**Comment by ralphhanna** [comment]
Ok, here is an example

<img width="1151" alt="Image" src="https://github.com/user-attachments/assets/a269fd96-9904-40a9-be39-a6e326029a37" />

Compliance has rejected, so it ends

**Comment by shashank-yelluri** [comment]
@ralphhanna - to be very honest, my workflow has not changed. Now, in your previous models, i can see you have 5 stages, now one thing is missing out here is, each stage can be another 6 different paths (like in your first stage), again each path can further have 6 more paths. That's how complicated it is, because, My first stage of approval will be like this, 

`1 from HR Team AND 1 from Compliance Team AND 1 from Legal Team AND ... upto 6 (Horizontally)
OR 
1 from Board Member AND 2 from Operations team AND  ...upto 6
OR
...upto 6 (Vertically)`

Now this entire thing should be under on stage. That is whole reason why i had to build my workflow so complicated. It is something like this, I've put in the inclusive gateway inside another inclusive gateway. I cannot use parallel, because i do not want to activate all the paths. This is because, i have given the flexibility to reach upto 6 levels horizontally & vertically, but it can have only one AND and one OR also. Hence in the model if you see, for every flow, i've added a condition.

**ISSUE**
Now the whole point of me opening this ticket is, when i have 5 different paths, my inclusive activates all of them. But whenever i choose a path and proceed, the user tasks in the rest of the paths are deactivated, but the tokens at the incluive gateways are still active. Due to which the workflow status is "running". 

I've added the reject also in my workflow, but differently. I feel your way of escalation is a better apporoach. Because, i have added one more flow for every user task to see the ACTION and move to parallel gateway if the action is approve otherwise reject.

Now to put it simple, i need your help in two things 🙏 
1. Tokens should not wait at the inclusive gateway (as the paths are already deactivated)
2. Scrap my reject approach in the model and try to ad your escalation approach. This is a huge ask, but if you could help me, that would be greatful 🙏 

Before this, 
Please go through the conditions in my model and the JSON i've shared with you previously for the "determineWorkflow" service tas. This is the important step to understand how token flows and what exactly i'm trying to solve. 

One last thing, I'm not sure whether i'm allowed to ask this, I've searched through the LinkedIn with your name, but i couldn't find any 😬 :( Is there anyway i can follow or connect ? It is all because of the respect that i carry towards you for all the help. If it is not professional. Let's keep the things same way 😃 

Thank You for reading this whole and speding lot of time on configuring my workflow. Have a good day 🙌 

Attaching the workflow for the reference, 

[authMatrix_V4.bpmn.txt](https://github.com/user-attachments/files/19037081/authMatrix_V4.bpmn.txt)

**Comment by bpmn-ts** [comment]
Hi
Sure you reach me at ***@***.***
I

**Comment by ralphhanna** [comment]
Hi @shashank-yelluri 
You can reach me at ralph hanna at hot mail dot com all one word no spaces

**Comment by shashank-yelluri** [comment]
`const userName = "ralphhanna";
const domainName = "hotmail";
const userMail = `${userName}@${domainName}.com`
`

Is this the one ?

**Comment by ralphhanna** [comment]
Regarding the Rules can we simplify the rules as such:
-Approval stage is multi stage
-Each Stage involves several teams
-Each team requires min number of users to approve
-We dynamically create n of items = total of min users
-We check at end of each item, if it the requirement are met based on logic like this
```ts
// rule for stage 1 
// ct is a map of completed teams

static checkRules1(ct:Map<TeamsEnum,any>): boolean {
  if (ct.has(TeamsEnum.BOARD_MEMBER) 
      && ct.has(TeamsEnum.CEO) 
      && ct.has(TeamsEnum.REGULATOR) 
      || (ct.has(TeamsEnum.VICE_PRESIDENT_TEAM) 
         && ct.has(TeamsEnum.SENIOR_OPS_TEAM)) 
    )
    return true;
}

 
```
this will proceed to next stage 
otherwise, it will wait 

This is in addition to 'reject' 

The model will look as clean as this:

<img width="737" alt="Image" src="https://github.com/user-attachments/assets/cc94e2e5-2af7-4c6d-9034-354abb607e96" />

**Comment by shashank-yelluri** [comment]
Can you run this down ? Initially the work item has to be offered for all the subRules in the rules[0]. If any one path completely approves, them we'll deactivate the rest and move forward. Can you please share me the BPMN also ? Along with your proposed rule structure. As i've been thinking this since a month, not able to think from your shoes. Please share me any appservices along with BPMN (along with your rules structure)

Please share them, if this situation fits in and gets solved with the above model 😆  

  [
            { Stage: "A",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Officers Team",
                      "minApprovers": 2
                    },
                    {
                      "groupName": "RM Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Operations Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Directors Team",
                      "minApprovers": 1
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "HR Head Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            { Stage: "B",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Risk Officers Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Compliance Officers Team",
                      "minApprovers": 2
                    }
                  ]
                }
              ]
            },
            { Stage: "C",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Treasury Head Team",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Finance Controllers Team",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            },
            {
		Stage: "D",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "CFO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Vice President Team",
                      "minApprovers": 2
                    }
                  ]
                },
                {
                  "subRules": [
                    {
                      "groupName": "Senior Ops Team",
                      "minApprovers": 3
                    }
                  ]
                }
              ]
            },
            {
		Stage: "E",
              "rules": [
                {
                  "subRules": [
                    {
                      "groupName": "Board Member",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "CEO",
                      "minApprovers": 1
                    },
                    {
                      "groupName": "Regulator",
                      "minApprovers": 1
                    }
                  ]
                }
              ]
            }
          ];
    }

**Comment by shashank-yelluri** [comment]
@ralphhanna - is there any way that we can write some information to the parent `data` object ? The data is being stored under `elementId` specific object.

**Comment by ralphhanna** [comment]
Hi @shashank-yelluri 
Ok, all done, here are the files

[Approval2.bpmn.txt](https://github.com/user-attachments/files/19041962/Approval2.bpmn.txt)

[ApprovalManager.ts.txt](https://github.com/user-attachments/files/19041973/ApprovalManager.ts.txt)
[appServices.ts.txt](https://github.com/user-attachments/files/19041972/appServices.ts.txt)

**Comment by shashank-yelluri** [comment]
@ralphhanna - GOD Level 🔥 
Just now tested and it is working fine. I need the entire day may be to understand 😆 
I need to add the service task on the final approvals and do some slight modifications. But this is psych and let me go through your work and get back to you 🙏 

Thank You Thank You again. Crazy !!

**Comment by shashank-yelluri** [comment]
@ralphhanna - also, one last question. I could see only two escalations. One is "approved" and second is "rejected", but there can be another scenario where we had only one stage of approvals. In that case, we need to probably add one more escalation of "completed" ? Because, once the flow is completed, this can be at stage 1 itself or in our example can go till stage 5. After this, i need to escalate and trigger one service task. 

How can i add that escalation ? Quick steps may be ? 😬 
This escalation is always a big doubt to me.

**Comment by shashank-yelluri** [comment]
@ralphhanna - kindly ignore. Figured it out. 

<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/31472b1d-283b-4d0c-97bf-664bf093b719" />

**Comment by shashank-yelluri** [comment]
@ralphhanna - one clarification. What is this,

static test() {

// Example Usage
const approvals: Record<string, number> = {
    "Treasury Officers Team": 2,
    "Finance Team": 1,
    "CFO": 1,
    "Vice President Team": 2
  };
  console.log(ApprovalManager.documentStageRules(null));
  
  console.log("Stage A Teams",ApprovalManager.getRequiredTeams(1)); 
  // { "Treasury Officers Team": 2, "RM Team": 1, "Finance Team": 2, "Operations Head Team": 1, "Directors Team": 1, "HR Head Team": 1 }
  
  console.log("Stage D Teams",ApprovalManager.getRequiredTeams(4)); 
  
  console.log("Stage A",approvals,ApprovalManager.isStageApproved(1, approvals)); // true or false
  console.log("Stage D",ApprovalManager.isStageApproved(4, approvals)); // true or false      
}

This code looks like my next problem also you've solved. 
1. I really need to simulate by giving the approvals. 
2. Which teams and what conditions is it waiting on ?
3. What is the flow it went through ?

Does this piece of code solves any of the above mentioned scenarios ?

**Comment by shashank-yelluri** [comment]
@ralphhanna - can we make the approvals drive from the service task ? Currently things are hardcoded in the file. But i want them to be driven from one service task.

**Comment by shashank-yelluri** [comment]
@ralphhanna - we are only able to access the data for the particular user task, 

How can we get the complete data ?

<img width="1232" alt="Image" src="https://github.com/user-attachments/assets/5c6d0b49-c476-4e72-80a7-b1764c2be9c1" />

**Comment by ralphhanna** [comment]
To Access Root data from inside any trigger:
```ts
context.token.execution.instance.data
```





<img width="739" alt="Image" src="https://github.com/user-attachments/assets/b89229db-08fb-40a1-b578-4a6d973393ad" />

**Comment by shashank-yelluri** [comment]
@ralphhanna - Great. But what if I want to invoke the task to store the data at root level ? Do we have that provision ?

**Comment by ralphhanna** [comment]
same way, `context.token.execution.instance.data['myVar']='my val'`

**Comment by ralphhanna** [comment]
Please update `npm update bpmn-server` should give 2.2.20
Latest release of your example files are here in new release of bpmn-web 2.2.20
-  New Model https://github.com/bpmnServer/bpmn-web/blob/main/src/test/processes/Multi-Stage%20Approval.bpmn
-  ApprovalManager.ts https://github.com/bpmnServer/bpmn-web/blob/main/src/WorkflowApp/ApprovalManager.ts
- AppServices.ts https://github.com/bpmnServer/bpmn-web/blob/main/src/WorkflowApp/appServices.ts
- Example Script https://github.com/bpmnServer/bpmn-web/blob/main/src/examples/complexApproval.ts

The Example script answer your questions above.
- Simulate data entry (use for testing)
- ListCases - as a report of all the cases
```ts
async function test() {

    await deleteCases(); // cleans all data for this model
    
    await simulate(data1);
    await simulate(data2);
    await simulate(data3);

    await listCases();  // produces a report
}
```

**Comment by shashank-yelluri** [comment]
@ralphhanna - Great. But in the newer release, could you please check your `package.json` ? `bpmn-server` package is pointing to some file in your local. Please cross check once. I've cloned it newly and got some crazy errors.

**Comment by shashank-yelluri** [comment]
@ralphhanna - one quick clarification, do we have an option to store only relevant details to our databases ? Like in wf_instances, we have a field of "logs", which i do not want to store. Also, i want to rename the collection name. How can we do these things ?

**Comment by ralphhanna** [comment]
New bpmn-web release is now fixed, you can always do `npm i bpmn-server` to fix this in the future.

Regarding not storing logs and renaming collection, please make that a 'New Feature Request'
Let us close this thread, is very long

**Comment by ralphhanna** [comment]
Hi @shashank-yelluri see #246

**Comment by ralphhanna** [comment]
Just for the record, we could have used Decision Table logic instead:

<img width="855" alt="Image" src="https://github.com/user-attachments/assets/28f899bf-9500-4a43-87de-062a8615c8e9" />

**Comment by shashank-yelluri-dn** [comment]
> Hi [@shashank-yelluri](https://github.com/shashank-yelluri) see [#246](https://github.com/bpmnServer/bpmn-server/issues/246)

Thank You @ralphhanna

**Comment by shashank-yelluri-dn** [comment]
> Just for the record, we could have used Decision Table logic instead:
> 
> <img alt="Image" width="855" src="https://private-user-images.githubusercontent.com/11893416/421526964-28f899bf-9500-4a43-87de-062a8615c8e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI4MDA4MDgsIm5iZiI6MTc0MjgwMDUwOCwicGF0aCI6Ii8xMTg5MzQxNi80MjE1MjY5NjQtMjhmODk5YmYtOTUwMC00YTQzLTg3ZGUtMDYyYTg2MTVjOGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI0VDA3MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjg3OGQyNzM5YTRkMWU1NGY1NGFkZTI4OTUwODk4N2JmNTg5MDBiYWVmOTFjYTk5MmQ3Y2Y5YmM3Yzk0ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mGaRZ6dymQOKTbIavyUlHGcn6dWdWltgFt1k22gfmYE">

How can we do this ? Can you share me the sample XML (if you have) ?
Thank You
